repos:
-   repo: local
    hooks:
    -   id: update-hugo-lastmod
        name: Update Hugo lastmod timestamp
        entry: python update_lastmod.py
        language: python
        types: [markdown]
        files: ^content/.*\.md$ # Add this line to restrict paths
        stages: [commit]
        pass_filenames: true